error: add comments and remove unused errors
This commit adds some comments for the .c and .h error files
and removes unused errors for handling with files.